language: generic

sudo: required
services: 
  - docker
before_install:
  - docker build -t arturserra/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true arturserra/react-test npm test

after_success:
  - docker build -t arturserra/multi-client ./client
  - docker build -t arturserra/multi-nginx ./nginx
  - docker build -t arturserra/multi-server ./server
  - docker build -t arturserra/multi-worker ./worker

  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images and push them to DockerHub
  - docker push arturserra/multi-client
  - docker push arturserra/multi-nginx
  - docker push arturserra/multi-server
  - docker push arturserra/multi-worker

  deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-850583700852
    bucket_path: docker-multi
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY